### ISSUE TITLE
اضافه کردن لینک راهنما در فایل README

### ISSUE THREAD

**Issue by ziaa** [kiamazi/mira#1]
اگه دوست داشتید لینک [مستندات](https://miraxy.github.io) رو هم به فایل
 [README](https://github.com/kiamazi/mira/blob/974cf69dfdee1c0a59d62f041973e15158c9bc1b/README.md) اضافه کنید.
به نظرم این‌جوری کار خوب‌تون، خوب‌تر میشه!

**Comment by kiamazi** [comment]
<div dir=rtl>
ممنون، اضافه شد.
</div>
